language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "openviglet_shiohara"
    token:
      secure: "X9Q63KJjmoC60D/Fm/ITUuzUs7K7Ms9Zyw0ZXPQGfIx5Ccb8HgWnr4Vo/ptVaX5Vylx4xaYaYB9Bo00tLWTMcrWUgO2fxlFiIqZvhQlt9QqE3+hoLfXnLb4U8FEcfLsbiSiCEe9nr+voXqnlXYoWuSGalBo3jED4HVt/S5QY7IKDcRLeI91HahybSpfV191zpC4uZwC9BnvlJXpnNMcPx7UJQWCejfmKjA37eCTN5KnJk9xcBBEV0TXyBPE+eI+og22u9cBkrJsc0XyR8rXCrCWpvfeE/U/v5kokqEDXt87QlQvzdbyRvyqS/nmSh0wYTNzZPGl37Lf+QIwHLoPhIVjBgj4o1Q8mpC1gcSeaAjSrDA4Mhx0AqKC855yq5/5kSX77dJQ8cYXH3Ipg0jG4BmsfdLttJvFcJ/zG3wQBHpAmtAykPsrZFNMpfw+y2OY4ct8ejR52r8eq+gRwBi8i/yScMIptoopeEq346pzNqcmzCznoZW0txooOhbB5J64nx2MF+dwU8iTSu9bElQyGL5xbqkr2aVgd/Ln7n3kvYqpuLHn6cEJ1QcQVcYjePmNEU3Kj7n8AVpjzDOFHt7gFv5QUi2OZ9N4X/U91owvNecqONUBeVbLuEmaAlvtDoQMh77vUCawINoJR29aMk5B1fPzZhZH31AZcg/Zm4aFntYs="
script: ./gradlew check
 - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
