version: '3'
services:
  shiohara-nginx:
    container_name: shiohara-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
  shiohara-mariadb:
    container_name: shiohara-mariadb
    image: mariadb    
    environment:
      MYSQL_DATABASE: viglet_shiohara
      MYSQL_ROOT_PASSWORD: viglet_shiohara
      MYSQL_USER: viglet_shiohara
      MYSQL_PASSWORD: viglet_shiohara
    ports:
    - 3306:3306
    restart: always
  shiohara:
    container_name: shiohara
    restart: always
    build: .  
    working_dir: /app  
    ports:
     - 2710:2710  
    depends_on:
      - shiohara-nginx
      - shiohara-mariadb
    command: java -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
    environment:     
      SPRING_DATASOURCE_URL: jdbc:mariadb://shiohara-mariadb:3306/viglet_shiohara
      SPRING_DATASOURCE_USERNAME: viglet_shiohara
      SPRING_DATASOURCE_PASSWORD: viglet_shiohara
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      
